# Generated by Django 5.1.4 on 2024-12-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song_title', models.CharField(max_length=150)),
                ('artist_name', models.CharField(max_length=100)),
                ('song_lyrics', models.TextField()),
                ('song_type', models.CharField(choices=[('Praise', 'PRAISE'), ('WORSHIP', 'Worship')], max_length=50)),
                ('song_chords', models.TextField()),
            ],
        ),
    ]
